"""PostgreSQL connector: information_schema discovery + strict read-only SQL.

Query envelope generated by the LLM for this engine:
    {"sql": "SELECT ...", "visualization_hint": "...", "query_summary": "..."}

Defense in depth for read-only enforcement:
  1. validate_query() — single SELECT/WITH statement, no write/DDL keywords
     (string literals are stripped before scanning so data containing words
     like 'DROP' doesn't false-positive), no comments, no stacked statements.
  2. The session runs with default_transaction_read_only=on, so anything that
     slips past the validator is still rejected by PostgreSQL itself.
  3. statement_timeout caps runaway queries.
"""

import json
import re

import psycopg
from psycopg.rows import dict_row

from app.connectors.base import BaseConnector, ConnectorError

STATEMENT_TIMEOUT_MS = 15000

# Rejected anywhere outside string literals (word-boundary match)
_BLOCKED_KEYWORDS = (
    "INSERT", "UPDATE", "DELETE", "DROP", "ALTER", "TRUNCATE", "GRANT",
    "REVOKE", "COPY", "CREATE", "MERGE", "CALL", "EXECUTE", "PREPARE",
    "DEALLOCATE", "DO", "VACUUM", "REINDEX", "CLUSTER", "REFRESH", "LOCK",
    "LISTEN", "NOTIFY", "SET", "RESET", "COMMENT", "SECURITY", "INTO",
)

# Dangerous functions (DoS / file access / server control)
_BLOCKED_FUNCTIONS = (
    "pg_sleep", "pg_read_file", "pg_read_binary_file", "pg_ls_dir",
    "pg_terminate_backend", "pg_cancel_backend", "lo_import", "lo_export",
    "dblink", "pg_reload_conf",
)

_ENUM_CARDINALITY = 12
_MAX_TABLES = 50


class PostgresConnector(BaseConnector):
    engine = "postgresql"

    def __init__(self, uri: str, database: str):
        super().__init__(uri, database)
        self._conn = None

    def _connection(self):
        if self._conn is None or self._conn.closed:
            self._conn = psycopg.connect(
                self.uri,
                dbname=self.database,
                connect_timeout=5,
                row_factory=dict_row,
                autocommit=True,
                options=(
                    f"-c default_transaction_read_only=on "
                    f"-c statement_timeout={STATEMENT_TIMEOUT_MS}"
                ),
            )
        return self._conn

    # -- Connection -----------------------------------------------------

    def test_connection(self) -> tuple[bool, str]:
        try:
            with self._connection().cursor() as cur:
                cur.execute(
                    "SELECT count(*) AS n FROM information_schema.tables "
                    "WHERE table_schema = 'public'"
                )
                n = cur.fetchone()["n"]
            return True, f"Connected to '{self.database}' ({n} tables)"
        except psycopg.Error as e:
            return False, str(e).strip()

    def close(self) -> None:
        if self._conn is not None and not self._conn.closed:
            self._conn.close()

    # -- Schema discovery -----------------------------------------------

    def discover_schema(self, sample_size: int = 100) -> dict:
        try:
            return {"engine": self.engine, "entities": self._discover_entities(sample_size)}
        except psycopg.Error as e:
            raise ConnectorError(f"Schema discovery failed: {e}") from e

    def _discover_entities(self, sample_size: int) -> list[dict]:
        conn = self._connection()
        with conn.cursor() as cur:
            cur.execute("""
                SELECT c.relname AS table_name, c.reltuples::bigint AS approx_count
                FROM pg_class c
                JOIN pg_namespace n ON n.oid = c.relnamespace
                WHERE n.nspname = 'public' AND c.relkind = 'r'
                ORDER BY c.relname
                LIMIT %s
            """, (_MAX_TABLES,))
            tables = cur.fetchall()

            cur.execute("""
                SELECT table_name, column_name, data_type, is_nullable
                FROM information_schema.columns
                WHERE table_schema = 'public'
                ORDER BY table_name, ordinal_position
            """)
            columns = cur.fetchall()

            cur.execute("""
                SELECT tc.table_name,
                       kcu.column_name,
                       ccu.table_name AS foreign_table,
                       ccu.column_name AS foreign_column
                FROM information_schema.table_constraints tc
                JOIN information_schema.key_column_usage kcu
                  ON tc.constraint_name = kcu.constraint_name
                 AND tc.table_schema = kcu.table_schema
                JOIN information_schema.constraint_column_usage ccu
                  ON tc.constraint_name = ccu.constraint_name
                 AND tc.table_schema = ccu.table_schema
                WHERE tc.constraint_type = 'FOREIGN KEY' AND tc.table_schema = 'public'
            """)
            fks = cur.fetchall()

        cols_by_table: dict[str, list[dict]] = {}
        for col in columns:
            cols_by_table.setdefault(col["table_name"], []).append(col)
        fks_by_table: dict[str, list[str]] = {}
        for fk in fks:
            fks_by_table.setdefault(fk["table_name"], []).append(
                f"{fk['column_name']} -> {fk['foreign_table']}.{fk['foreign_column']}"
            )

        entities = []
        for t in tables:
            name = t["table_name"]
            fields = {}
            for col in cols_by_table.get(name, []):
                info: dict = {"types": [col["data_type"]]}
                if col["is_nullable"] == "YES":
                    info["nullable"] = True
                self._add_value_hints(name, col, info, sample_size)
                fields[col["column_name"]] = info
            approx = t["approx_count"]
            if approx <= 0:  # reltuples is -1/0 until the table is analyzed
                approx = self._bounded_count(name)
            entity = {
                "name": name,
                "approx_count": approx,
                "fields": fields,
            }
            if fks_by_table.get(name):
                entity["foreign_keys"] = sorted(fks_by_table[name])
            entities.append(entity)
        return entities

    def _bounded_count(self, table: str) -> int:
        """Exact count capped at 100k so discovery stays cheap on huge tables."""
        try:
            with self._connection().cursor() as cur:
                cur.execute(f'SELECT count(*) AS n FROM (SELECT 1 FROM "{table}" LIMIT 100000) t')
                return cur.fetchone()["n"]
        except psycopg.Error:
            self._conn = None
            return 0

    def _add_value_hints(self, table: str, col: dict, info: dict, sample_size: int) -> None:
        """Sample a column for enum-like values (text) or example values."""
        if col["data_type"] not in (
            "text", "character varying", "character",
            "integer", "bigint", "numeric", "real", "double precision",
            "date", "timestamp without time zone", "timestamp with time zone", "boolean",
        ):
            return
        ident = f'"{table}"."{col["column_name"]}"'
        try:
            with self._connection().cursor() as cur:
                if col["data_type"] in ("text", "character varying", "character"):
                    cur.execute(
                        f'SELECT DISTINCT {ident} AS v FROM "{table}" '
                        f"WHERE {ident} IS NOT NULL LIMIT {_ENUM_CARDINALITY + 1}"
                    )
                    values = [r["v"] for r in cur.fetchall()]
                    if 0 < len(values) <= _ENUM_CARDINALITY:
                        info["values"] = sorted(values)
                    elif values:
                        info["examples"] = values[:3]
                else:
                    cur.execute(f'SELECT {ident} AS v FROM "{table}" WHERE {ident} IS NOT NULL LIMIT 3')
                    info["examples"] = [r["v"] for r in cur.fetchall()]
        except psycopg.Error:
            self._conn = None  # drop a possibly-broken connection; hints are best-effort

    # -- Validation (read-only enforcement) ------------------------------

    def validate_query(self, query: dict, schema: dict) -> tuple[bool, str]:
        if "sql" not in query or not isinstance(query["sql"], str) or not query["sql"].strip():
            return False, "Missing required field: sql"

        sql = query["sql"].strip().rstrip(";").strip()

        if "--" in sql or "/*" in sql or "*/" in sql:
            return False, "Blocked: SQL comments are not allowed"

        stripped = _strip_string_literals(sql)

        if ";" in stripped:
            return False, "Blocked: multiple statements are not allowed"

        first_word = re.match(r"\s*(\w+)", stripped)
        if not first_word or first_word.group(1).upper() not in ("SELECT", "WITH"):
            return False, f"Blocked operation: only SELECT queries are allowed (got {first_word.group(1) if first_word else 'empty'!s})"

        upper = stripped.upper()
        for kw in _BLOCKED_KEYWORDS:
            if re.search(rf"\b{kw}\b", upper):
                return False, f"Blocked keyword: {kw}"
        for fn in _BLOCKED_FUNCTIONS:
            if re.search(rf"\b{fn}\b", stripped, re.IGNORECASE):
                return False, f"Blocked function: {fn}"

        return True, ""

    # -- Execution --------------------------------------------------------

    def execute(self, query: dict, max_results: int = 0) -> dict:
        sql = query["sql"].strip().rstrip(";")
        cap = max_results if max_results > 0 else None
        try:
            with self._connection().cursor() as cur:
                cur.execute(sql)
                rows = cur.fetchmany(cap) if cap else cur.fetchall()
        except psycopg.Error as e:
            self._conn = None  # reconnect next time; the session may be aborted
            raise ConnectorError(str(e).strip()) from e
        results = [_jsonable(dict(r)) for r in rows]
        return {"results": results, "count": len(results)}

    # -- Prompt material ----------------------------------------------------

    def query_instructions(self) -> str:
        return """## Required JSON Schema
{
    "sql": "string — a single PostgreSQL SELECT statement",
    "visualization_hint": "string — one of: table, number, list, bar_chart, pie_chart, none",
    "query_summary": "string — brief plain-language description of the query"
}

## PostgreSQL Rules
1. Use ONLY tables and columns that exist in the schema above. Respect the
   foreign_keys hints when joining tables.
2. Exactly ONE statement. ONLY SELECT (a WITH ... SELECT CTE is fine).
   NEVER INSERT, UPDATE, DELETE, DROP, ALTER, TRUNCATE, GRANT, COPY, CREATE,
   SELECT INTO, or any other write/DDL operation.
3. Do NOT use SQL comments (-- or /* */) anywhere.
4. JOINs, GROUP BY, ORDER BY, HAVING, subqueries, and window functions are allowed.
5. Add LIMIT only when the user asks for a specific number of results (e.g. top 5).
6. For case-insensitive text search use ILIKE.
7. Use explicit column lists or aliases so result columns have readable names.
8. Pick the visualization_hint that best fits the expected result shape:
   - single value -> number, grouped totals -> bar_chart or pie_chart,
   - record listings -> table, short name lists -> list."""

    def few_shot_examples(self) -> str:
        examples = [
            {
                "q": "How many employees do we have?",
                "a": {
                    "sql": "SELECT count(*) AS employee_count FROM employees",
                    "visualization_hint": "number",
                    "query_summary": "Counted all employees",
                },
            },
            {
                "q": "Average salary per department",
                "a": {
                    "sql": (
                        "SELECT d.name AS department, round(avg(e.salary), 2) AS avg_salary "
                        "FROM employees e JOIN departments d ON d.id = e.department_id "
                        "GROUP BY d.name ORDER BY avg_salary DESC"
                    ),
                    "visualization_hint": "bar_chart",
                    "query_summary": "Average salary grouped by department",
                },
            },
            {
                "q": "Top 5 highest paid employees with their department",
                "a": {
                    "sql": (
                        "SELECT e.first_name, e.last_name, e.title, e.salary, d.name AS department "
                        "FROM employees e JOIN departments d ON d.id = e.department_id "
                        "ORDER BY e.salary DESC LIMIT 5"
                    ),
                    "visualization_hint": "table",
                    "query_summary": "Top 5 employees by salary",
                },
            },
            {
                "q": "How many people were hired each year?",
                "a": {
                    "sql": (
                        "SELECT extract(year FROM hire_date)::int AS year, count(*) AS hires "
                        "FROM employees GROUP BY year ORDER BY year"
                    ),
                    "visualization_hint": "bar_chart",
                    "query_summary": "Hires per year",
                },
            },
        ]
        return "\n".join(f"Q: {e['q']}\nA: {json.dumps(e['a'], indent=2)}" for e in examples)


def _strip_string_literals(sql: str) -> str:
    """Remove '...' (with '' escapes) and $tag$...$tag$ literals so keyword
    scanning can't be fooled by data values, and string contents can't hide
    statement separators."""
    out = []
    i = 0
    n = len(sql)
    while i < n:
        ch = sql[i]
        if ch == "'":
            i += 1
            while i < n:
                if sql[i] == "'":
                    if i + 1 < n and sql[i + 1] == "'":  # escaped ''
                        i += 2
                        continue
                    i += 1
                    break
                i += 1
            out.append("''")
            continue
        if ch == "$":
            m = re.match(r"\$(\w*)\$", sql[i:])
            if m:
                tag = m.group(0)
                end = sql.find(tag, i + len(tag))
                if end == -1:
                    return "".join(out)  # unterminated; rest is literal
                i = end + len(tag)
                out.append("''")
                continue
        out.append(ch)
        i += 1
    return "".join(out)


def _jsonable(row: dict) -> dict:
    """Coerce Postgres types (Decimal, date, ...) into JSON-friendly values."""
    from datetime import date, datetime
    from decimal import Decimal

    for k, v in row.items():
        if isinstance(v, Decimal):
            row[k] = float(v)
        elif isinstance(v, (datetime, date)):
            row[k] = v.isoformat()
    return row
